mainapp/urls.py
from django.urls import path
from . import  views
from django.contrib.auth.decorators import login_required

#pip lines for the project
urlpatterns = [
    path('create_note/', login_required(views.create_note), name='create_note'),
    path('read_notes/', login_required(views.read_notes), name='read_notes'),
    path('detail_note/<int:id>/', login_required(views.detail_note), name='detail_note'),
    path('delete_note/<int:id>/', login_required(views.delete_note), name='delete_note'),
    path('edit_note/<int:id>/', login_required(views.edit_note), name='edit_note'),
    path('search/', login_required(views.search_notes), name='search_notes'),
]

notes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from mainapp.views import read_notes
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(read_notes), name='read_notes'),
    path('',include('mainapp.urls')),
    path('',include('user_system.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_system/urls.py
from django.urls import path
from user_system.views import custom_login,user_logout,register
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('login/', login_required(custom_login), name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', register, name='register'),
]

mainapp/models.py
from django.db import models
from cloudinary.models import CloudinaryField

# Note Model


class NoteModel(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    screen_shoot = CloudinaryField('image', null=True, blank=True)
    def __str__(self):
        return self.title

user_system/models.py
from django.db import models

# Create your models here.

mainapp/forms.py
from django import forms
from mainapp.models import NoteModel

#NOTE FORM
class NoteForm(forms.ModelForm):
    class Meta:
        model = NoteModel
        fields = ('title','content','screen_shoot')

user_system/forms.py
from django import forms
from django.contrib.auth.models import User

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

mainapp/views.py
from django.shortcuts import render
from mainapp.forms import NoteForm
from django.shortcuts import render,redirect
from django.contrib import messages
# Create your views here.
from django.contrib import messages
from .forms import NoteForm  # Import your NoteForm
from .models import NoteModel

from django.contrib import admin
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required


def dashboard_callback(request, context):
    context.update({
        "custom_variable": "value",  # Add any other variables you want to pass
    })
    return context


class CustomAdminSite(admin.AdminSite):
    site_header = "My Custom Admin"
    site_title = "Admin"
    index_title = "Dashboard"

    def index(self, request, extra_context=None):
        context = super().index(request, extra_context)
        context = dashboard_callback(request, context)
        return context


admin_site = CustomAdminSite(name='custom_admin')
def create_note(request):
    if request.method == 'POST':
        form = NoteForm(request.POST, request.FILES)  # Need to include request.FILES for file uploads
        if form.is_valid():
            form.save()
            messages.success(request, 'Note submitted successfully!')
            return redirect('read_notes')
    else:
        form = NoteForm()

    # Pass the form to the template context in both cases
    context = {'form': form}
    return render(request, 'mainapp/create_notes.html', context)


#read all the notes

@login_required(login_url='login/')  # Redirects to custom login if not authenticated
def read_notes(request):
    notes=NoteModel.objects.all()
    context = {'notes':notes}
    return render(request, 'mainapp/read_notes.html', context)
#detail of notes
def detail_note(request,id):
    note=NoteModel.objects.get(pk=id)
    context = {'note':note}
    return render(request,'mainapp/detail_note.html',context)

def delete_note(request,id):
    if request.method == 'POST':
        note = NoteModel.objects.get(pk=id)
        note.delete()
        messages.success(request, 'note has been deleted..')
        return redirect('read_notes')
    else:
        note = NoteModel.objects.get(pk=id)
        context = {'note':note}
        return render(request, 'mainapp/delete_note.html')

    #edit notes
def edit_note(request, id):
    if request.method == 'POST':
        note = NoteModel.objects.get(pk=id)
        messages.success(request, 'note has been edited..')
        return redirect('read_notes')
    else:
        note = NoteModel.objects.get(pk=id)
        context = {'note': note}
        return render(request, 'mainapp/edite_note.html', context)


def search_notes(request):
    query = request.GET.get('query')
    if query:
        notes = NoteModel.objects.filter(title__icontains=query)
    else:
        notes = []
    return render(request, 'mainapp/search_notes.html', {'notes': notes, 'query': query})

user_system/views.py
# views.py

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib import messages

def custom_login(request):
    if request.user.is_authenticated:
        messages.success(request, 'You are already logged in.')
        return redirect('read_notes')  # Adjust this to your actual redirect after login
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Successfully logged in.')
                return redirect('read_notes')  # Adjust this to your desired URL
            else:
                return render(request, 'user_system/login.html', {'error': 'Invalid username or password'})
        else:
            return render(request, 'user_system/login.html')

def user_logout(request):
    logout(request)
    return redirect('login')  # Redirect to login page after logout

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'User has been registered successfully.')
            return redirect('login')  # Redirect to login page after registration
    else:
        form = UserCreationForm()
    return render(request, 'user_system/register.html', {'form': form})

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <style>
      body {
        height: 100%;
        margin-bottom: 100%;
        padding: 0;
      }
    </style>

    <link rel="stylesheet" href="{% static 'css/custom_styles.css' %}" />

    <link
      href="https://cdn.jsdelivr.net/npm/tailwindcss@^2/dist/tailwind.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'bootstrap/css/read_note.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'bootstrap/css/create_note.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'bootstrap/css/bootstrap.min.css' %}"
    />
    <title href="{% url 'read_notes' %}">NotesPrograming</title>
  </head>
  <body>
    <div>{% include 'mainapp/navbar.html' %}</div>
    <div>
      {% block content %} {% endblock%}
      <script src="{% static 'bootstrap/js/bootstrap.min.js.bundle' %}"></script>
      <script src="{% static 'bootstrap/js/change.js' %}"></script>
    </div>
    {% include 'mainapp/footer.html' %}
  </body>
</html>

mainapp/templates/mainapp/create_notes.html
{% extends 'mainapp/base.html' %} {% block content %}
<style>
  .form-control {
    transition: border-color 0.3s, border-width 0.3s; /* Smooth transition */
  }

  .form-control:hover {
    border-color: #007bff; /* Change this to your desired hover color */
    border-width: 2px; /* Increase border width on hover */
  }
</style>

<div class="container mt-5">
  <h2 class="text-center mb-4">Create a Note</h2>

  <div class="form-errors">
    {% if form.errors %}
    <ul class="alert alert-danger">
      {% for field, errors in form.errors.items %} {% for error in errors %}
      <li><strong>{{ field }}:</strong> {{ error }}</li>
      {% endfor %} {% endfor %}
    </ul>
    {% endif %}
  </div>

  <div
    class="note-form p-4 bg-light shadow-lg rounded"
    style="max-width: 600px; margin: 0 auto"
  >
    <form method="post" enctype="multipart/form-data" class="form">
      {% csrf_token %}
      <div class="form-group mb-3">
        <label for="id_title" class="form-label fw-bold">Title</label>
        <input
          type="text"
          name="title"
          id="id_title"
          class="form-control border border-primary shadow-sm"
          value="{{ form.title.value|default_if_none:'' }}"
        />
      </div>
      <div class="form-group mb-3">
        <label for="id_content" class="form-label fw-bold">Content</label>
        <textarea
          name="content"
          id="id_content"
          class="form-control border border-success shadow-sm"
        >
{{ form.content.value|default_if_none:'' }}</textarea
        >
      </div>
      <div class="form-group mb-3">
        <label for="id_screen_shoot" class="form-label fw-bold"
          >Screenshot</label
        >
        <input
          type="file"
          name="screen_shoot"
          id="id_screen_shoot"
          class="form-control border border-info shadow-sm"
        />
      </div>
      <button type="submit" class="btn btn-primary mb-3 rounded-pill shadow">
        Embed Note
      </button>
    </form>
  </div>
</div>
{% endblock %}

mainapp/templates/mainapp/custom_form_admin_user.html
{% extends 'unfold/layouts/base_simple.html' %} {% block content %}
<div class="container mx-auto p-4">
  <h1 class="text-2xl font-bold mb-6">Add User</h1>
  <form
    method="POST"
    action="{% url 'admin:auth_user_add' %}"
    class="bg-white p-6 rounded-lg shadow-md"
  >
    {% csrf_token %}
    <div class="mb-4">
      <label for="id_username" class="block text-sm font-medium text-gray-700"
        >Username:</label
      >
      <input
        type="text"
        name="username"
        id="id_username"
        required
        class="mt-1 block w-full p-2 border border-gray-300 rounded-md focus:ring focus:ring-blue-200"
      />
    </div>
    <div class="mb-4">
      <label for="id_password1" class="block text-sm font-medium text-gray-700"
        >Password:</label
      >
      <input
        type="password"
        name="password1"
        id="id_password1"
        required
        class="mt-1 block w-full p-2 border border-gray-300 rounded-md focus:ring focus:ring-blue-200"
      />
    </div>
    <div class="mb-4">
      <label for="id_password2" class="block text-sm font-medium text-gray-700"
        >Password Confirmation:</label
      >
      <input
        type="password"
        name="password2"
        id="id_password2"
        required
        class="mt-1 block w-full p-2 border border-gray-300 rounded-md focus:ring focus:ring-blue-200"
      />
    </div>
    <div class="flex justify-end">
      <button
        type="submit"
        class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-200"
      >
        Add User
      </button>
    </div>
  </form>
</div>
{% endblock %}

mainapp/templates/mainapp/delete_note.html
{% extends 'mainapp/base.html' %} {% block content %}
<h1>Delete Note</h1>
<p>Are you sure you want to delete this note?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger mb-3">Confirm Delete</button>
  <a href="{% url 'read_notes' %}">Cancel</a>
</form>
{% endblock %}

mainapp/templates/mainapp/detail_note.html
{% extends 'mainapp/base.html' %}
{% block content %}
<div class="container-xl mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-lg-12 d-flex align-items-center justify-content-center">
            <img src="{{ note.screen_shoot.url }}" class="img-fluid rounded" alt="..." style="border-radius: 15px;">
          </div>
          <div class="col-lg-6">
            <div class="card-body">
              <h1 class="card-title">{{ note.title }}</h1>
              <p class="card-text" style="font-size: 1.5rem;">{{ note.content }}</p>
              <a href="{% url 'read_notes' %}" class="btn btn-primary">Go back</a> <!-- Added "Go back" button -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

mainapp/templates/mainapp/edite_note.html
{% extends 'mainapp/base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Note</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="title">Title:</label>
                            <input type="text" class="form-control" id="title" name="title" value="{{ note.title }}" required>
                        </div>
                        <div class="form-group">
                            <label for="content">Content:</label>
                            <textarea class="form-control" id="content" name="content" rows="4" required>{{ note.content }}</textarea>
                        </div>
                        {% if note.screen_shoot.url %}
                            <img src="{{ note.screen_shoot.url }}" class="img-fluid" alt="Screenshot">
                        {% endif %}
                        <button style="margin-top: 5px" type="submit" class="btn btn-primary">Save Changes</button>
                        <a href="{% url 'read_notes' %}" style="margin-top: 5px" type="submit" class="btn btn-primary">go back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/footer.html
<footer class="bg-dark text-white py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
        <p>&copy; 2024 My Notes App. All rights reserved.</p>
        <p>Contact us: <a href="mailto:ajoyia360@gmail.com" class="text-white">ajoyia360@gmail.com</a></p>
      </div>
      <div class="col-md-6 text-center text-md-end">
        <ul class="list-inline mb-0">
          <li class="list-inline-item"><a href="#" class="text-white">Privacy Policy</a></li>
          <li class="list-inline-item"><a href="#" class="text-white">Terms of Service</a></li>
          <li class="list-inline-item"><a href="#" class="text-white">FAQ</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

mainapp/templates/mainapp/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Notes App</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
    /* Custom styles */
    .navbar-dark {
      background-color: #343a40 !important;
    }
    .navbar-dark .navbar-nav .nav-link {
      color: rgba(255, 255, 255, 0.5);
    }
    .navbar-dark .navbar-nav .nav-link:hover {
      color: rgba(255, 255, 255, 0.75);
    }
  </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark">
  <a class="navbar-brand" href="{% url 'read_notes' %}">My Notes App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'create_note' %}">Add Note</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'read_notes' %}">Read Note</a>
      </li><li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Register user</a>
      </li>
      <!-- Add the following list item for the search bar -->
      <li class="nav-item">
        <form class="form-inline my-2 my-lg-0" action="{% url 'search_notes' %}" method="GET">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </li>
      <!-- End of added list item for the search bar -->
    </ul>
      {% if request.user.is_authenticated %}
       <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
      {% else %}
           <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

mainapp/templates/mainapp/note/change_form.html
<!-- templates/admin/mainapp/note/change_form.html -->
{% extends "admin/change_form.html" %} {% block content %}
<div class="formWrapper">
  <h2>{{ title }}</h2>
  <form method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %} {{ adminform.form.as_p }}
    <button type="submit">Save</button>
  </form>
</div>
{% endblock %}

mainapp/templates/mainapp/read_notes.html
{% extends 'mainapp/create_notes.html' %} {% block content %} {% if messages %}
{% for message in messages %}
<div class="alert alert-primary" role="alert">{{ message }}</div>
{% endfor %} {% endif %}
<div class="container mt-5 border-5 border-success">
  <div class="card notes-container mb-4">
    <!-- Added mb-4 class for bottom margin -->
    <div class="card-body">
      <div class="row">
        {% for note in notes %}
        <div class="col-md-6 mb-4">
          <div class="card">
            <div class="card-body mb-5">
              <h2 class="card-title">{{ note.title }}</h2>
              <p class="card-text">{{ note.content }}</p>
              {% if note.screen_shoot %}
              <img
                src="{{ note.screen_shoot.url }}"
                class="card-img-top border rounded shadow"
                alt="Screenshot"
              />
              {% endif %}
              <a
                href="{% url 'detail_note' note.id %}"
                class="btn btn-primary btn-sm mt-2 rounded-pill"
                >Details</a
              >
              <a
                href="{% url 'delete_note' note.id %}"
                class="btn btn-danger btn-sm mt-2 rounded-pill"
                >Delete</a
              >
              <a
                href="{% url 'edit_note' note.id %}"
                class="btn btn-secondary btn-sm mt-2 rounded-pill"
                >Edit</a
              >
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

mainapp/templates/mainapp/search_notes.html
{% extends 'mainapp/base.html' %} {% block content %}
<div class="container">
  <h1 class="mt-5">Search Notes</h1>
  <form class="mt-4 mb-4" method="get" action="{% url 'search_notes' %}">
    <div class="input-group">
      <input
        type="text"
        class="form-control"
        name="query"
        placeholder="Search by title"
        value="{{ query }}"
      />
      <div class="input-group-append">
        <button class="btn btn-primary" type="submit">Search</button>
      </div>
    </div>
  </form>
  <hr />

  {% if notes %}
  <h2>Search Results</h2>
  <div class="row">
    {% for note in notes %}
    <div class="col-md-4 mb-4">
      <!-- Adjust the column width here -->
      <div class="card shadow-sm">
        <div class="card-body">
          <h5 class="card-title">{{ note.title }}</h5>
          <a href="{% url 'detail_note' note.id %}" class="btn btn-primary border rounded"
            >View Note</a
          >
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <p>No notes found.</p>
  {% endif %}
</div>
{% endblock %}

user_system/templates/user_system/login.html
{% extends 'mainapp/base.html' %}
{% block content %}
<div class="container-fluid h-100" style="margin-top: 50px;">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-center mb-4">Login</h2>
                    {% if error %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endif %}
                <div class="container ">
                    <form style="padding-bottom: -90px" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control" name="username" placeholder="Username">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" name="password" placeholder="Password">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </form>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user_system/templates/user_system/register.html
{% extends 'mainapp/base.html' %}
{% block content %}
<div class="container" style="margin-top: 50px;">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" class="user-form" style="background-color: #f9f9f9; padding: 20px; border-radius: 5px; box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);">
                {% csrf_token %}
                <h2 class="text-center mb-4">Register User</h2>
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary btn-block mt-4">Add User</button>
                <a href="{% url 'read_notes' %}" class="btn btn-primary btn-block mt-2">Go Back</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}